### ISSUE TITLE
undefined reference to `interfaceX::interfaceX()'

### ISSUE THREAD

**Issue by deepblueparticle** [MrCrazyID/QtCreator_SubDirExample#2]
There is an error in running the code: SubTestProject/projectA/main.cpp:11: error: undefined reference to `interfaceX::interfaceX()'

**Comment by idelsink** [comment]
Hi @deepblueparticle can you give me some more information? I checked out the project and found out that I never added unix support. That's the only issue I had with this project. 
I tried it out using a Windows VM (I'm using Linux) with QT version `5.10.1` and with the latest master branch (38f099015a30ff5d63efd04bbe6e4eadafd6cffb) and it all works.

Are you using a unix like system?

**Comment by deepblueparticle** [comment]
Hi @idelsink, I redownloaded the repo and it works! There must be sth not configured properly last time. I use Ubuntu. Thanks for your great work.
